#!/bin/bash
set -e

# Install Quarto (not pre-installed on Binder)
QUARTO_VERSION="1.10.3"
wget -qO quarto.tar.gz \
  "https://github.com/quarto-dev/quarto-cli/releases/download/v${QUARTO_VERSION}/quarto-${QUARTO_VERSION}-linux-amd64.tar.gz"
mkdir -p "$HOME/.local/quarto"
tar -xzf quarto.tar.gz -C "$HOME/.local/quarto" --strip-components=1
rm quarto.tar.gz
echo 'export PATH="$HOME/.local/quarto/bin:$PATH"' >> "$HOME/.bashrc"
